server:
  port: 8762

eureka:
  instance:
    hostname: localhost
#eureka可以同时作为服务端和客户端，这里禁用掉他客户端的能力
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#关闭自我保护机制，以确保注册中心将不可用的实例及时正确剔除
  server:
    enable-self-preservation: false